### ISSUE TITLE
ART insert may crash in some case

### ISSUE THREAD

**Issue by yizhang2077** [flode/ARTSynchronized#8]
Hi!
I find in some case, art insert API may be crashed.  In the following example, I insert two keys and the program will abort
```
#include "ART/Tree.h"
#include <vector>
#include <string>

std::vector<std::string > dict{
  "art",
  "artist",
};

void loadKey(TID tid, Key &key) {
  key.set((const char*)dict[tid].data(), dict[tid].size());
}

void singlethreaded() {

  ART_unsynchronized::Tree tree(loadKey);
  std::vector<TID> keys = {0 , 1};
  for (uint64_t i = 0; i != keys.size(); i++) {
      Key key;
      loadKey(keys[i], key);
      tree.insert(key, keys[i]);
  }
}

int main(){
  singlethreaded();
}
```
I find if we insert a key whose prefix is a inserted key, the **Tree.cpp:123** may have some trouble
```
n4->insert(k[level + prefixLength], N::setLeaf(tid));
n4->insert(key[level + prefixLength], nextNode);
```
The **level + prefixLength** is out of range and will case **Key** operator[] raising error.

**Comment by mmarkakis** [comment]
I believe this is by design, and mentioned in the README: https://github.com/flode/ARTSynchronized#execution-instructions

**Comment by yizhang2077** [comment]
> I believe this is by design, and mentioned in the README: https://github.com/flode/ARTSynchronized#execution-instructions

Thank you,I think you are right
